# Generated by Django 4.1.2 on 2023-03-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_images', models.URLField()),
                ('aritist_key', models.CharField(max_length=100, verbose_name='アーティスト')),
            ],
        ),
        migrations.CreateModel(
            name='Janru_middle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janru_name', models.CharField(max_length=50, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Janru_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janru_name', models.CharField(max_length=50, verbose_name='ジャンル名')),
            ],
        ),
        migrations.CreateModel(
            name='Janru_spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janru_name', models.CharField(max_length=50, verbose_name='ジャンル名')),
                ('janru_ID', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='ジャンルID')),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janru', models.CharField(max_length=50, verbose_name='ジャンル')),
                ('keyword', models.CharField(max_length=100, verbose_name='キーワード')),
                ('music', models.CharField(max_length=100, verbose_name='楽曲名')),
                ('artist', models.CharField(max_length=50, verbose_name='アーティスト名')),
                ('al_images', models.URLField()),
                ('page_num', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='ページ数')),
                ('popularity', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='人気順')),
                ('rank', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='順位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
