# Generated by Django 4.1.2 on 2023-05-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_rename_janru_main_genru'),
    ]

    operations = [
        migrations.CreateModel(
            name='artists',
            fields=[
                ('aritsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='アーティスト名')),
                ('aritsts_images', models.URLField()),
                ('aritsts_uri', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='genre_spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ManyToManyField(to='mypage.genre')),
            ],
        ),
        migrations.CreateModel(
            name='musics',
            fields=[
                ('musics_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='音楽名')),
                ('spotify_uuid', models.UUIDField()),
                ('aritist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.artists')),
            ],
        ),
        migrations.CreateModel(
            name='musics_in_playlist',
            fields=[
                ('musics_in_playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('musics_images', models.URLField()),
                ('musics_uri', models.URLField()),
                ('musics_id', models.ManyToManyField(to='mypage.musics')),
            ],
        ),
        migrations.CreateModel(
            name='playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='プレイリストネーム')),
                ('user_id', models.IntegerField()),
                ('Public', models.BooleanField()),
                ('description', models.TextField()),
                ('Creation_Date', models.DateTimeField()),
                ('Updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='search_results',
            fields=[
                ('search_results_id', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.JSONField(blank=True, null=True)),
                ('keyword', models.CharField(max_length=1000, verbose_name='キーワード')),
                ('page_num', models.IntegerField()),
                ('musics_id', models.CharField(max_length=100, verbose_name='楽曲名')),
                ('artists_id', models.CharField(max_length=100, verbose_name='アーティスト名')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.genre')),
            ],
        ),
        migrations.CreateModel(
            name='spotify_genre',
            fields=[
                ('spotify_genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ジャンル')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ユーザ名')),
                ('spotify_account', models.CharField(max_length=100, verbose_name='ユーザアカウント')),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Janru_middle',
        ),
        migrations.DeleteModel(
            name='Janru_search',
        ),
        migrations.DeleteModel(
            name='Janru_spotify',
        ),
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.DeleteModel(
            name='result',
        ),
        migrations.AddField(
            model_name='playlists',
            name='playlists_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.users'),
        ),
        migrations.AddField(
            model_name='musics_in_playlist',
            name='playlists_id',
            field=models.ManyToManyField(to='mypage.playlists'),
        ),
        migrations.AddField(
            model_name='genre_spotify',
            name='spotify_genre_id',
            field=models.ManyToManyField(to='mypage.spotify_genre'),
        ),
    ]
