# Generated by Django 4.1.2 on 2023-05-07 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_rename_keyword_search_results_keyword_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlists',
            name='Creation_Date',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='Updated',
        ),
        migrations.AddField(
            model_name='playlists',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playlists',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='search_results',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='search_results',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
