# Generated by Django 4.1.2 on 2023-05-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_rename_keyword_id_search_results_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotify_genre',
            name='type',
        ),
        migrations.AlterField(
            model_name='search_results',
            name='genre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mypage.genre'),
        ),
    ]
