# Generated by Django 4.1.2 on 2023-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_remove_spotify_genre_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='spotify_uuid',
            field=models.CharField(max_length=100),
        ),
    ]
