# Generated by Django 4.1.2 on 2023-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0010_remove_musics_in_playlist_musics_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='Public',
            field=models.BooleanField(default=True),
        ),
    ]
