# Generated by Django 4.1.2 on 2023-09-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0012_artists_artist_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='music',
            field=models.ManyToManyField(to='mypage.musics'),
        ),
    ]
